[package]
name = "rattan"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
[workspace]
members = ['.', 'rattan-core']
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/stack-rs/rattan"
repository = "https://github.com/stack-rs/rattan"
rust-version = "1.86"

[workspace.dependencies]
ctrlc = "3.2.5"
figment = { version = "0.10", features = ["toml", "env", "json"] }
futures = "0.3.29"
human-bandwidth = { version = "0.1.4", features = ["serde", "binary-system"] }
jiff = "0.2.15"
netem-trace = { version = "0.4.3", features = ["serde", "human", "mahimahi"] }
nix = { version = "0.29.0", features = [
  "time",
  "net",
  "event",
  "ioctl",
  "mount",
  "sched",
  "signal",
] }
once_cell = "1.19"
rand = "0.9.1"
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.26.0", features = [
  "rt-multi-thread",
  "time",
  "net",
  "sync",
  "signal",
  "tokio-macros",
  "macros",
] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[features]
default = ["first-packet"]
first-packet = ["rattan-core/first-packet"]
http = ["rattan-core/http"]
packet-dump = ["rattan-core/packet-dump"]

[dependencies]
# anyhow = "1.0.75"
# bollard = "0.15.0"
clap = { version = "4.2.4", features = ["derive"] }
ctrlc = { workspace = true }
dirs = "6.0.0"
figment = { workspace = true }
futures = { workspace = true }
human-bandwidth = { workspace = true }
jiff = { workspace = true }
netem-trace = { workspace = true }
nix = { workspace = true }
once_cell = { workspace = true }
paste = "1.0.14"
rand = { workspace = true }
rattan-core = { path = "rattan-core", features = ["serde"] }
serde = { workspace = true }
serde_json = "1.0.114"
tokio = { workspace = true }
toml = "0.9.2"
tracing = { workspace = true }
tracing-appender = "0.2.3"
tracing-subscriber = { workspace = true }

# required for cargo flamegraph
[profile.release]
debug = true

# required for cargo flamegraph
[profile.dev]
debug = true
opt-level = 0
