[RepeatedBwPatternConfig]
count = 0

[[RepeatedBwPatternConfig.pattern]]

[RepeatedBwPatternConfig.pattern.StaticBwConfig]
bw = "32Mbps"
duration = "1s"

[[RepeatedBwPatternConfig.pattern]]

[RepeatedBwPatternConfig.pattern.RepeatedBwPatternConfig]
count = 45

[[RepeatedBwPatternConfig.pattern.RepeatedBwPatternConfig.pattern]]

[RepeatedBwPatternConfig.pattern.RepeatedBwPatternConfig.pattern.TraceBwConfig]
pattern = [["100ms", ["16Mbps", "48Mbps"]]]

[[RepeatedBwPatternConfig.pattern]]

[RepeatedBwPatternConfig.pattern.StaticBwConfig]
bw = "32Mbps"
duration = "1s"
