name: CI

on:
  push:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: cargo build with all features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --all-features

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy --all-features

  test-all-features:
    name: cargo test with all features
    strategy:
      fail-fast: false
      matrix:
        kernel: [ 5.4, 5.15, 6.1 ]
    runs-on: ${{ matrix.kernel }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get install -y iproute2 ethtool iputils-ping iperf3
      - run: CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER='sudo -E' cargo test --all-features
        env:
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: 'sudo -E'
