name: CI

on:
  push:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: cargo build with all features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --all-features

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy --all-features

  audit:
    name: Run cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/audit@v1

  test-all-features:
    name: cargo test with all features
    strategy:
      fail-fast: false
      matrix:
        kernel: [ 5.4, 5.15, 6.1, 6.6 ]
    runs-on: ${{ matrix.kernel }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get install -y iproute2 ethtool iputils-ping iperf3 datamash bc
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - run: cargo nextest run --profile ci --all-features
        env:
          RUST_LOG: 'info'
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: 'sudo -E'
      - run: sudo ./rattan/tests/scripts/clean_stdenv.sh -a
      - name: Performance verification
        run: |
          /bin/bash ./ci/scripts/verify.sh
          cd ./ci/scripts/ && tar -czf cache/verify_log.tar.gz cache/*.log
      - name: Archive verification results
        uses: actions/upload-artifact@v3
        with:
          name: verification_${{ matrix.kernel }}
          path: |
            ci/scripts/cache/verify.html
            ci/scripts/cache/verify_log.tar.gz
